apiVersion: v1
data:
  prometheus.yml: >-
	##########################

	# GLOBAL CONFIGURATION

	##########################

	global:
  	scrape_interval: 	15s # Set the scrape interval to every 15 seconds.
  	evaluation_interval: 15s # Evaluate rules every 15 seconds.
  	scrape_timeout:  	10s  

	scrape_configs:
  
  	- job_name: 'prometheus'
    	# metrics_path defaults to '/metrics'
    	# scheme defaults to 'http'.
    	static_configs:
    	- targets: ['localhost:9090']

  	# JAEGER METRICS COLLECT
  	- job_name: "jaeger-metrics"
    	tls_config:
      	insecure_skip_verify: true
    	metrics_path: /metrics
    	scrape_interval: 5s
    	scheme: http
    	static_configs:
    	- targets: ['jaeger-mon.openbanking-monitoring-tracing.svc:14269']
   	 
  	# 3SCALE APICAST PRODUCTION
  	- job_name: "apicast-production-metrics"
    	tls_config:
      	insecure_skip_verify: true
    	metrics_path: /metrics
    	scrape_interval: 5s
    	scheme: http
    	static_configs:
    	- targets:
      	- apicast-production.3scale-api-mgmt.svc:9421
     	 

	##########################

	# INFLUXDB CONFIGURATION

	##########################


	remote_write:
  	- url: 'http://influxdb-mon:8086/api/v1/prom/write?db=prometheus'
    	name: prom_write

	remote_read:
  	- url: 'http://influxdb-mon:8086/api/v1/prom/read?db=prometheus'
    	name: prom_read
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: openbanking-monitoring-prometheus
